[build]
 functions = "functions"

[functions]
  # Directory with serverless functions, including background
  # functions, to deploy. This is relative to the base directory
  # if one has been set, or the root directory if
  # a base hasn’t been set.
  directory = "functions/"
  node_bundler = "esbuild"

# Use [dev] to set configuration overrides for local 
# development environments run using Netlify Dev - except 
# for environment variables. Environment variables for Netlify 
# Dev should be set under [context.dev.environment] instead.
[dev]
  publish = "dist"